/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//RCC
#define RCC_BASE	0x40021000
#define RCC_APB2ENR	*(volatile uint32_t *)(RCC_BASE +0x18) //enable GPIO portA clock
//GPIO portA
#define GPIOA_BASE	0x40010800
#define GPIOA_CRH	*(volatile uint32_t *)(GPIOA_BASE +0x04)
#define GPIOA_ODR	*(volatile uint32_t *)(GPIOA_BASE +0x0C)
#define GPIOA_CRL	*(volatile uint32_t *)(GPIOA_BASE)

//AFIO
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_BASE +0x08)
//EXTI
#define EXTI_BASE	0x40010400
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_BASE +0x08)
#define EXTI_IMR *(volatile uint32_t *)(EXTI_BASE)
#define EXTI_PR *(volatile uint32_t *)(EXTI_BASE +0x14)

#define NVIC_ISER *(volatile uint32_t *)(0xE000E100)


void GPIOA_PIN13_OUTPUT()
{
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
}

void GPIOA_PIN0_INPUT()
{
	GPIOA_CRL |= (1<<2);
}
void clock_init()
{
	RCC_APB2ENR |= 1<<2;
	RCC_APB2ENR |= 1;
}

int main(void)
{
	clock_init();
	GPIOA_PIN13_OUTPUT();
	GPIOA_PIN0_INPUT();
	//Rising trigger selection for line 0
	EXTI_RTSR |= 1;
	//Interrupt Mask on line 0
	EXTI_IMR |= 1;
	//Select portA for EXTI0
	AFIO_EXTICR1 = 0x0;
	//Enable NVIC IRQ6 (EXTI0)
	NVIC_ISER |= (1<<6);

    /* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler()
{
	GPIOA_ODR ^= 1<<13;

	EXTI_PR |= 1;
}

