/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC   0x40021000
#define PortA 0x40010800
#define PortA_CRH   *((volatile uint32_t*)(PortA+0x04))
#define PortA_ODR   *((volatile uint32_t*)(PortA+0x0C))
#define RCC_APB2ENR *((volatile uint32_t*)(RCC+0x18))
/***** another way to access ODR *****/
typedef union{
	struct{
		volatile uint32_t Reserved:13;
		volatile uint32_t Pin13:1;
	}SPIN;
	volatile uint32_t All_Pins;
	
}UODR_t;
volatile UODR_t* R_ODR = (volatile UODR_t*)(PortA + 0x0C);
/************************************/
int main(void)
{
	RCC_APB2ENR |= (1<<2);
	PortA_CRH &= 0xFF0FFFFF;
	PortA_CRH |= 0x00200000;
	int i;
	while(1)
	{
		PortA_ODR |= (1<<13);
		for(i=0 ; i<50000 ; i++);
		PortA_ODR &= ~(1<<13);
		for(i=0 ; i<5000 ; i++);
	}

}
