/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>


#define RCC_BASE 0x40021000
#define RCC_CR   *(volatile uint32_t *)(RCC_BASE)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE +0x04)

void clock_init(){
	    /*Bits 1:0 SW: System clock switch
		00: HSI selected as system clock
		01: HSE selected as system clock
		10: PLL selected as system clock <--
		11: not allowed*/
		RCC_CFGR |= (0b10<<0);

		//RCC_CFGR:
		/*Bits 21:18 PLLMUL: PLL multiplication factor
		0000: PLL input clock x 2
		0001: PLL input clock x 3
		0010: PLL input clock x 4
		0011: PLL input clock x 5
		0100: PLL input clock x 6
		0101: PLL input clock x 7
		0110: PLL input clock x 8 <--
		0111: PLL input clock x 9*/
		RCC_CFGR |= (0b110<<18);

		/*Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
		0xx: HCLK not divided
		100: HCLK divided by 2 <--
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16*/
		RCC_CFGR |= (0b100<<11);

		/*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
		100: HCLK divided by 2 <--
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16*/
		RCC_CFGR |= (0b100<<8);

		//RCC_CR:
		/*Bit 24 PLLON: PLL enable
		0: PLL OFF
		1: PLL ON*/
		RCC_CR |= (1<<24);
}
int main(void)
{
	clock_init();
    /* Loop forever */
	while(1);
}
