/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile unsigned int*)(RCC_BASE+0x18)

//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile unsigned int*)(GPIOA_BASE+0x00)
#define GPIOA_CRH *(volatile unsigned int*)(GPIOA_BASE+0x04)
#define GPIOA_IDR *(volatile unsigned int*)(GPIOA_BASE+0x08)

//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(volatile unsigned int*)(GPIOB_BASE+0x00)
#define GPIOB_CRH *(volatile unsigned int*)(GPIOB_BASE+0x04)
#define GPIOB_ODR *(volatile unsigned int*)(GPIOB_BASE+0x0C)

void clock_init()
{
	//Bit 2 IOPAEN: I/O port A clock enable
	RCC_APB2ENR |= (1<<2);
	//Bit 3 IOPBEN: I/O port B clock enable
	RCC_APB2ENR |= (1<<3);
}
void GPIO_init()
{
	/***PortA1***/
	//MODE: 00: Input mode
	GPIOA_CRL &= ~(0b11<<4);
	//CNF: 01: Floating input
	GPIOA_CRL |= (0b01<<6);

	/***PortA13***/
	//MODE: 00: Input mode
	GPIOA_CRH &= ~(0b11<<20);
	//CNF: 01: Floating input
	GPIOA_CRH |= (0b01<<22);

	/***PortB1***/
	//MODE: 01: Output mode, max speed 10 MHz.
	GPIOB_CRL |= (0b01<<4);
	//CNF: 00: General purpose output push-pull.
	GPIOB_CRL &= ~(0b11<<6);

	/***PortB13***/
	//MODE: 01: Output mode, max speed 10 MHz.
	GPIOB_CRH |= (0b01<<20);
	//CNF: 00: General purpose output push-pull.
	GPIOB_CRH &= ~(0b11<<22);
}
void Waiting(unsigned int x)
{
	int i,j;
	for(i=0 ; i<x ; i++)
		for(j=0 ; j<255 ; j++);

}
int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		if((GPIOA_IDR & (1<<1))>>1 == 0)
		{
			GPIOB_ODR ^= (1<<1);
			//To make it single press
			while((GPIOA_IDR & (1<<1))>>1 == 0);
		}

		if((GPIOA_IDR & (1<<13))>>13 == 1)
		{
			GPIOB_ODR ^= (1<<13);
		}

		Waiting(1);
	}

}
